@startuml CommentManager

class CommentManager{

    + addComment(Comment Comment, User user)
    + updateComment(Comment Comment, User user)
    + deleteComment(Comment Comment, User user)
    + createListingComment(Comment Comment)
    + moderateComment(Comment Comment User user)

}