@startuml MessageManager

class MessageManager{

    + addMessage(Message Message, User user)
    + updateMessage(Message Message, User user)
    + deleteMessage(Message Message, User user)
    + createListingMessage(Message Message)
    + moderateMessage(Message message User user)

}