@startuml Trick

!include Comment.puml
!include User.puml 
!include Image.puml 
!include Video.puml 
!include Trickgroup.puml
!include TrickManager.puml
!include CommentManager.puml
!include UserManager.puml
!include ImageManager.puml
!include VideoManager.puml

Class Trick {
    
    - name : string
    - slug : string
    - description : string
    - date : Datetime
    
}

Image *--"1" Trick: have <
Video *--"1" Trick: have <
Trickgroup "1"-* Trick: have <
Trick *--"1" User: create <
Trick "1"-* Comment: have <>

Comment *--"1" User: add <
TrickManager -- Trick: exec
ImageManager -- Image: exec
VideoManager -- Video: exec
CommentManager -- Comment: exec
UserManager - User: exec

@enduml
