@startuml Trick

!include Comment.puml 
!include User.puml 
!include Trickgroup.puml
!include TrickManager.puml
!include CommentManager.puml
!include UserManager.puml

Class Trick {
    
    - name : string
    - slug : string
    - description : string
    - picture : string
    - video : string
    - date : Datetime
    
}

Trickgroup "1"-* Trick: have <
Trick *--"1" User: create <
Trick "1"-* Comment: have <>
Comment *--"1" User: create <
TrickManager -- Trick: exec
CommentManager -- Comment: manage
User - CommentManager: moderate
UserManager - User: exec

@enduml
