@startuml UserSequence

skinparam responseCommentBelowArrow true
skinparam SequenceCommentAlignment center

actor User as User #Plum

entity Trick as Trick #LightYellow
entity Comment as Comment #LightYellow
entity Admin as Admin #LightYellow

database SnowTricks as SnowTricks #HotPink

User -> SnowTricks: créer un compte
alt cas réussi
SnowTricks-> User: valider création du compte
else email déjà existant 
SnowTricks-> User: échec de l'inscription

User -> SnowTricks: demander authentification 
SnowTricks-> User: valider authentification 
else identification invalides
SnowTricks-> User: échec de l'authentification

User -> SnowTricks: demander réinitialisation mot de passe
SnowTricks-> User: mail de réinitialisation

User -> SnowTricks: réinitialiser mot de passe 
SnowTricks-> User: valider réinitialisation 
else nom invalide
SnowTricks-> User: échec de la réinitialisation

User -> Trick: ajouter Trick 
Trick-> User: Trick ajouter 
else cette Trick existe déjà
SnowTricks-> User: échec de l'ajout

User -> Trick: modifier Trick 
else 403
Trick -> User: Vous n'avez pas accès à cette ressource

User -> Comment: ajouter Comment
Comment -> User: Comment en attente de validation
User -> Comment: consulter tous ses Comments


end
@enduml